### PR TITLE
Send 404 when env is invalid. Don't use default importmap file. Resolves #96

### LINKED ISSUE #96: Non Existent Envoirnments in Conf.js should return error instead of returning the default envoirnment settings
I have configured two envoirnment in my conf.js with below file which are working fine when i get and patch import-map.json but it always returns sit1 file for wrong envoirnment like sit3 and sit4 which are not even existing in conf.js , ideally it should throw error if wrong envoirnment name is passed in the query string

Below url still works which should not work 
**import-map.json?env=sit3**
```
module.exports = {
manifestFormat: "importmap",
packagesViaTrailingSlashes: false,
locations: {
sit1: "/www/mfe-sit/sit1/microfrontends/import-map.json",
sit2: "/www/mfe-sit/sit2/microfrontends/import-map.json",
},
};
```

### PR DESCRIPTION
**Pull request by joeldenning**
See #96. This PR is a breaking change and will be released as a major version. The breaking changes are that it no longer creates an empty import map at `import-map.json` when it receives a request to an invalid environment - instead it sends a 404. Additionally, it now uses `fs/promises` and `async` functions, which aren't supported in old versions of node.

I've always found the import-map-deployer's behavior confusing when it creates and uses a local file `import-map.json` instead of sending a 404. Receiving an empty import map response is something that has confused me and others, so I'm looking forward to this change

### CODE REVIEW

File: src/cache-control.js [hunk 1]
```diff
@@ -1,6 +1,7 @@
-const { config } = require("./config");
+const { getConfig } = require("./config");
```
Comment (joeldenning) [inline src/cache-control.js:1]: `getConfig` is preferred because the tests programmatically change the `config` object and so wrapping it in a function avoids using a stale config object.

File: src/io-methods/default.js [hunk 2]
```diff
@@ -1,30 +1,26 @@
 "use strict";
 const _ = require("lodash");
-const fs = require("./filesystem");
+const filesystem = require("./filesystem");
```
Comment (joeldenning) [inline src/io-methods/default.js:3]: I found the naming `fs` to be confusing, since `fs` is a builtin module in NodeJS. So I renamed this.

File: src/io-methods/default.js [hunk 3]
```diff
@@ -1,30 +1,26 @@
...
-    : "sofe-manifest.json";
-
 function getFilePath(env) {
+  const config = getConfig();
   if (_.has(config, ["locations", env])) {
     return config.locations[env];
   } else if (_.has(config, ["locations", "default"])) {
     return config.locations.default;
-  } else if (!_.isEmpty(config.locations)) {
+  } else if (!env && !_.isEmpty(config.locations)) {
```
Comment (joeldenning) [inline src/io-methods/default.js:16]: Only use the first environment in the config as the default, if the request doesn't specify an environment. If the request does specify an environment, only use that one.

File: src/io-methods/default.js [hunk 4]
```diff
@@ -1,30 +1,26 @@
...
     return config.locations[Object.keys(config.locations)[0]];
   } else {
-    return defaultFilePath;
+    throw Error(`No such environment '${env}'. Check your configuration file.`);
```
Comment (joeldenning) [inline src/io-methods/default.js:19]: This is the breaking change - I've always found it confusing that instead of sending 404 it would send you an empty import map from a default file. This is the breaking change part, but i think will be a better DX.

File: src/io-methods/filesystem.js [hunk 5]
```diff
@@ -1,47 +1,17 @@
...
-const fs = require("fs");
-const config = require("../config").config;
+const fs = require("fs/promises");
+const { getConfig } = require("../config");
 const jsHelpers = require("./js-file-helpers.js");
 
 exports.readManifest = function (filePath) {
-  return new Promise((resolve, reject) => {
-    //create file if not already created
-    fs.open(filePath, "a", function (err, fd) {
```
Comment (joeldenning) [inline src/io-methods/filesystem.js:9]: No longer create the file if it doesn't exist. Instead, throw an error if it doesn't exist.

File: src/io-methods/filesystem.js [hunk 6]
```diff
@@ -1,47 +1,17 @@
 "use strict";
-const fs = require("fs");
-const config = require("../config").config;
+const fs = require("fs/promises");
```
Comment (joeldenning) [inline src/io-methods/filesystem.js:2]: Use `fs/promises` to avoid all the errback/promise tension.

File: src/io-methods/filesystem.js [hunk 7]
```diff
@@ -1,47 +1,17 @@
...
-        jsHelpers.createJsString(data),
-        function (err) {
-          if (err) reject(`Could not write file ${filePath}`);
-          else resolve();
-        }
-      );
-    }
-  });
-
-  return Promise.all([jsonPromise, jsPromise]);
```
Comment (joeldenning) [inline src/io-methods/filesystem.js:46]: I just simplified the implementation approach here. The Promise.all was a race condition as it was potentially writing the file twice, depending on configuration.

File: src/web-server.js [hunk 8]
```diff
@@ -58,11 +58,13 @@ app.use(auth);
 app.use(express.static(__dirname + "/public"));
 
 function getEnv(req) {
-  if (req.query.env === undefined) {
-    return "default";
-  } else {
-    return req.query.env;
-  }
+  return req.query.env;
```
Comment (joeldenning) [inline src/web-server.js:61]: By leaving `req.query.env` as `undefined` (instead of changing it to `"default"`), we're now aware of the difference between an omitted env query param and one that was specified. When it's omitted, we use the default env. When it was specified, we do not use the default env.

File: src/web-server.js [hunk 9]
```diff
@@ -58,11 +58,13 @@ app.use(auth);
...
+}
+
+function sendError(res, ex, prefix) {
+  const status =
+    ex && ex.message && /No such environment/.test(ex.message) ? 404 : 500;
```
Comment (joeldenning) [inline src/web-server.js:66]: Perhaps a bit code-smelly, but this is the logic that determines whether to send a 404 or 500.

File: test/import-map.test.js [hunk 10]
```diff
@@ -188,4 +188,54 @@ describe(`/import-map.json`, () => {
     expect(response.body.imports.b).not.toBeDefined();
     expect(response.body.imports["b/"]).not.toBeDefined();
   });
+
+  it(`returns a 404 when you try to retrieve an import map for an environment that doesn't exist`, async () => {
```
Comment (joeldenning) [inline test/import-map.test.js:192]: None of these new tests were passing until i made the corresponding changes to the source.
