### PR TITLE
Fix issue with gcp bucket/key regex. Resolves #99.

### LINKED ISSUE #99: Can't host import map inside a folder in google cloud storage
Import map deploy doesn't support a path like gs://bucketname/prod/importmap.json. It throws a 404 error and dies.

But it works when file is hosted directly inside the bucket.

image

### PR DESCRIPTION
**Pull request by joeldenning**
See #99.

```js
// Old code that's incorrect
var [_, bucket, key] = /^(?:google|gs):\/\/(.+)\/(.+)$/.exec('gs://bucketname/prod/importmap.json')
console.log("bucket", bucket, "key", key) // "bucket" "bucketname/prod" "key" "importmap.json"

// New code that's correct
var [_, bucket, key] = /^(?:google|gs):\/\/(.+?)\/(.+)$/.exec('gs://bucketname/prod/importmap.json')
console.log("bucket", bucket, "key", key) // "bucket" "bucketname" "key" "prod/importmap.json"
```

### CODE REVIEW

File: src/io-methods/google-cloud-storage.js [hunk 1]
```diff
@@ -2,7 +2,7 @@ const { Storage } = require("@google-cloud/storage");
 
 const storage = new Storage();
 
-const regex = /^(?:google|gs):\/\/(.+)\/(.+)$/;
+const regex = /^(?:google|gs):\/\/(.+?)\/(.+)$/;
```
Comment (joeldenning) [inline src/io-methods/google-cloud-storage.js:5]: See https://javascript.info/regexp-greedy-and-lazy

Comment (frehner) [reply src/io-methods/google-cloud-storage.js:5]: that's a great article! thanks.

**Review by frehner — APPROVED** [review]
